

<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
    <li><a href="https://#Section_1">Instructions</a></li>
    <li><a href="https://#Section_2">About the Data</a></li>
    <li><a href="https://#Section_3">Importing Data </a></li>
    <li><a href="https://#Section_4">Data Preprocessing</a> </li>
    <li><a href="https://#Section_5">One Hot Encoding </a></li>
    <li><a href="https://#Section_6">Train and Test Data Split </a></li>
    <li><a href="https://#Section_7">Train Logistic Regression, KNN, Decision Tree, SVM, and Linear Regression models and return their appropriate accuracy scores</a></li>
</a></li>
</div>
<!-- <p>Estimated Time Needed: <strong>180 min</strong></p> -->
</div>

<hr>


# Instructions


In this notebook


Below, is where we are going to use the classification algorithms to create a model based on our training data and evaluate our testing data using evaluation metrics 

We will use some of the algorithms , specifically:

1. Linear Regression
2. KNN
3. Decision Trees
4. Logistic Regression
5. SVM

We will evaluate our models using:

1.  Accuracy Score
2.  Jaccard Index
3.  F1-Score
4.  LogLoss
5.  Mean Absolute Error
6.  Mean Squared Error
7.  R2-Score

Finally, you will use your models to generate the report at the end. 


# About The Dataset


The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)




This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



## **Import the required libraries**


In [1]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1
# Note: If your environment doesn't support "!mamba install", use "!pip install"

In [2]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [3]:
#you are running the lab in your  browser, so we will install the libraries using ``piplite``
import piplite
await piplite.install(['pandas'])
await piplite.install(['numpy'])


In [4]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

### Importing the Dataset


In [5]:
from pyodide.http import pyfetch

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

In [6]:
path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [7]:
await download(path, "Weather_Data.csv")
filename ="Weather_Data.csv"

In [8]:
df = pd.read_csv("Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

### Data Preprocessing


#### One Hot Encoding


First, we need to perform one hot encoding to convert categorical variables to binary variables.


In [9]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])


Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.


In [10]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

### Training Data and Test Data


Now, we set our 'features' or x values and our Y or target variable.


In [11]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [12]:
df_sydney_processed = df_sydney_processed.astype(float)

In [13]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

### Linear Regression


#### Q1) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.


In [14]:
#Enter Your Code, Execute and take the Screenshot
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features,Y,test_size=0.2,random_state=10)
# X=features

In [15]:
print("Train set :",x_train.shape,y_train.shape)
print('Test set:',x_test.shape,y_test.shape)

Train set : (2616, 66) (2616,)
Test set: (655, 66) (655,)


#### Q2) Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).


In [16]:
#Enter Your Code, Execute and take the Screenshot 

In [17]:
LinearReg = LinearRegression()
LinearReg.fit(x_train,y_train)
print("coeffiecients : ",LinearReg.coef_)

coeffiecients :  [-2.36898597e-02  1.29940794e-02  7.28447952e-04  6.49240382e-03
 -3.51631991e-02  4.23792566e-03  1.82829608e-03  7.89765488e-04
  9.53916720e-04  8.56268440e-03  7.69456986e-03 -9.24129706e-03
 -8.87456290e-03  1.00485529e-02  1.44566610e-02 -3.45969933e-03
  2.56837450e+10  2.56837450e+10 -6.20590195e+09 -6.20590195e+09
 -6.20590195e+09 -6.20590195e+09 -6.20590195e+09 -6.20590195e+09
 -6.20590195e+09 -6.20590195e+09 -6.20590195e+09 -6.20590195e+09
 -6.20590195e+09 -6.20590195e+09 -6.20590195e+09 -6.20590195e+09
 -6.20590195e+09 -6.20590195e+09  1.15377956e+10  1.15377956e+10
  1.15377956e+10  1.15377956e+10  1.15377956e+10  1.15377956e+10
  1.15377956e+10  1.15377956e+10  1.15377956e+10  1.15377956e+10
  1.15377956e+10  1.15377956e+10  1.15377956e+10  1.15377956e+10
  1.15377956e+10  1.15377956e+10 -2.10745217e+09 -2.10745217e+09
 -2.10745217e+09 -2.10745217e+09 -2.10745217e+09 -2.10745217e+09
 -2.10745217e+09 -2.10745217e+09 -2.10745217e+09 -2.10745217e+09
 -2.1074

#### Q3) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [18]:
#Enter Your Code, Execute and take the Screenshot

In [19]:
predictions = LinearReg.predict(x_test)
print("residual sum of squares: %.2f" % np.mean((predictions - y_test) ** 2))
print("Variance score: %.2f" % LinearReg.score(x_test, y_test))


residual sum of squares: 0.12
Variance score: 0.43


#### Q4) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [20]:
#Enter Your Code, Execute and take the Screenshot

In [21]:
from sklearn.metrics import r2_score
LinearRegression_MAE = np.mean(np.absolute(predictions - y_test))
LinearRegression_MSE = np.mean((predictions - y_test)**2)
LinearRegression_R2 = r2_score(predictions,y_test)


In [28]:
print("Mean Absolute Error : %.2f"%LinearRegression_MAE)
print("Mean squared Error :%.2f"%LinearRegression_MSE)
print("R2 Score :%.2f"%LinearRegression_R2)

Mean Absolute Error : 0.26
Mean squared Error :0.12
R2 Score :-0.38


#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [38]:
dict = [["LinearRegression_MAE",LinearRegression_MAE],["LinearRegression_MSE",LinearRegression_MSE],
       ["LinearRegression_R2",LinearRegression_R2]]
Report = pd.DataFrame(dict)
print(Report)

                      0         1
0  LinearRegression_MAE  0.256319
1  LinearRegression_MSE  0.115721
2   LinearRegression_R2 -0.384717


### KNN


#### Q6) Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.


In [ ]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [44]:
K = 4
KNN = KNeighborsClassifier(n_neighbors=K)
KNN.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

#### Q7) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [ ]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [46]:
predictions = KNN.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q8) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [ ]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [52]:
KNN_Accuracy_Score = metrics.accuracy_score(predictions,y_test)
KNN_JaccardIndex = metrics.jaccard_score(predictions,y_test)
KNN_F1_Score = metrics.f1_score(predictions,y_test)

print('Accuracy Score : %.2f'%KNN_Accuracy_Score)
print('Jaccard Score : %.2f'%KNN_JaccardIndex)
print('F1 Score : %.2f'%KNN_F1_Score)


Accuracy Score : 0.82
Jaccard Score : 0.43
F1 Score : 0.60


### Decision Tree


#### Q9) Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [54]:
Tree = DecisionTreeClassifier(criterion='entropy',max_depth=4)
Tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

#### Q10) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [56]:
predictions = Tree.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q11) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [64]:
Tree_Accuracy_Score = metrics.accuracy_score(predictions,y_test)
Tree_JaccardIndex = metrics.jaccard_score(predictions,y_test)
Tree_F1_Score = metrics.f1_score(predictions,y_test)
print("Accuracy Score : %.2f"%Tree_Accuracy_Score)
print("Jaccard Score : %.2f"%Tree_JaccardIndex)
print("F1 Score: %.2f"%Tree_F1_Score)

Accuracy Score : 0.82
Jaccard Score : 0.48
F1 Score: 0.65


### Logistic Regression


#### Q12) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [67]:
x_train, x_test, y_train, y_test = train_test_split(features,Y,test_size=0.2,random_state=1)
print("Train set :",x_train.shape,y_train.shape)
print("Test set:",x_test.shape,y_test.shape)

Train set : (2616, 66) (2616,)
Test set: (655, 66) (655,)


#### Q13) Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [69]:
LR = LogisticRegression(solver="liblinear")
LR.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

#### Q14) Now, use the `predict` and `predict_proba` methods on the testing data (`x_test`) and save it as 2 arrays `predictions` and `predict_proba`.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [72]:
predictions = LR.predict(x_test)
predictions[0:5]

array([0., 0., 0., 0., 0.])

In [73]:
predict_proba = LR.predict_proba(x_test)
predict_proba[0:5]

array([[0.74010003, 0.25989997],
       [0.97550665, 0.02449335],
       [0.52853719, 0.47146281],
       [0.85318912, 0.14681088],
       [0.96864347, 0.03135653]])

#### Q15) Using the `predictions`, `predict_proba` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [ ]:
#Enter Your Code, Execute and take the Screenshot

In [78]:
LR_Accuracy_Score = metrics.accuracy_score(predictions,y_test)
LR_JaccardIndex = metrics.jaccard_score(predictions,y_test)
LR_F1_Score = metrics.f1_score(predictions,y_test)
LR_Log_Loss = metrics.log_loss(predictions,y_test)
print("Accuracy Score :%.2f"%LR_Accuracy_Score)
print("Jaccard Score :%.2f"%LR_JaccardIndex)
print("F1 Score :%.2f"%LR_F1_Score)
print("Log Loss :%.2f"%LR_Log_Loss)

Accuracy Score :0.84
Jaccard Score :0.51
F1 Score :0.67
Log Loss :5.89


### SVM


#### Q16) Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).


In [ ]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [82]:
SVM = svm.SVC(kernel = "linear")
SVM.fit(x_train,y_train)

SVC(kernel='linear')

#### Q17) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [ ]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [85]:
predictions = SVM.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q18) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [87]:
SVM_Accuracy_Score = metrics.accuracy_score(predictions,y_test)
SVM_JaccardIndex = metrics.jaccard_score(predictions,y_test)
SVM_F1_Score = metrics.f1_score(predictions,y_test)
print("Accuracy score:%.2f"%SVM_Accuracy_Score)
print("Jaccard score:%.2f"%SVM_JaccardIndex)
print("F1 score:%.2f"%SVM_F1_Score)

Accuracy score:0.83
Jaccard score:0.50
F1 score:0.66


### Report


#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [89]:
dict1 = {'LinearRegression' : [LinearRegression_MAE,LinearRegression_MSE,LinearRegression_R2],
         'KNN' : [KNN_Accuracy_Score,KNN_JaccardIndex,KNN_F1_Score],
         'DecisionTree' : [Tree_Accuracy_Score,Tree_JaccardIndex,Tree_F1_Score],
         'LogisticRegression' : [LR_Accuracy_Score,LR_JaccardIndex,LR_F1_Score],
         'SVM' : [SVM_Accuracy_Score,SVM_JaccardIndex,SVM_F1_Score]
        }
dict2 = [["LinearRegression_MAE",LinearRegression_MAE],["LinearRegression_MSE",LinearRegression_MSE],
         ["LinearRegression_R2",LinearRegression_R2],
         ["KNN_Accuracy_Score",KNN_Accuracy_Score],["KNN_JaccardIndex",KNN_JaccardIndex],
         ["KNN_F1_Score",KNN_F1_Score],
         ["Tree_Accuracy_Score",Tree_Accuracy_Score],["Tree_JaccardIndex",Tree_JaccardIndex],
         ["Tree_F1_Score",Tree_F1_Score],
         ["LR_Accuracy_Score",LR_Accuracy_Score],["LR_JaccardIndex",LR_JaccardIndex],
         ["LR_F1_Score",LR_F1_Score],["LR_log_Loss",LR_Log_Loss],
         ["SVM_Accuracy_Score",SVM_Accuracy_Score],["SVM_JaccardIndex",SVM_JaccardIndex],
         ["SVM_F1_Score",SVM_F1_Score]]
Report = pd.DataFrame(data=dict2)
print(Report)

                       0         1
0   LinearRegression_MAE  0.256319
1   LinearRegression_MSE  0.115721
2    LinearRegression_R2 -0.384717
3     KNN_Accuracy_Score  0.818321
4       KNN_JaccardIndex  0.425121
5           KNN_F1_Score  0.596610
6    Tree_Accuracy_Score  0.818321
7      Tree_JaccardIndex  0.480349
8          Tree_F1_Score  0.648968
9      LR_Accuracy_Score  0.836641
10       LR_JaccardIndex  0.509174
11           LR_F1_Score  0.674772
12           LR_log_Loss  5.888047
13    SVM_Accuracy_Score  0.833588
14      SVM_JaccardIndex  0.495370
15          SVM_F1_Score  0.662539
